// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/api/http.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.google.api;

@kotlin.jvm.JvmName("-initializecustomHttpPattern")
public inline fun customHttpPattern(block: com.google.api.CustomHttpPatternKt.Dsl.() -> kotlin.Unit): com.google.api.CustomHttpPattern =
  com.google.api.CustomHttpPatternKt.Dsl._create(com.google.api.CustomHttpPattern.newBuilder()).apply { block() }._build()
/**
 * ```
 * A custom pattern is used for defining custom HTTP verb.
 * ```
 *
 * Protobuf type `google.api.CustomHttpPattern`
 */
public object CustomHttpPatternKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.google.api.CustomHttpPattern.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.api.CustomHttpPattern.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.api.CustomHttpPattern = _builder.build()

    /**
     * ```
     * The name of this custom HTTP verb.
     * ```
     *
     * `string kind = 1;`
     */
    public var kind: kotlin.String
      @JvmName("getKind")
      get() = _builder.getKind()
      @JvmName("setKind")
      set(value) {
        _builder.setKind(value)
      }
    /**
     * ```
     * The name of this custom HTTP verb.
     * ```
     *
     * `string kind = 1;`
     */
    public fun clearKind() {
      _builder.clearKind()
    }

    /**
     * ```
     * The path matched by this custom verb.
     * ```
     *
     * `string path = 2;`
     */
    public var path: kotlin.String
      @JvmName("getPath")
      get() = _builder.getPath()
      @JvmName("setPath")
      set(value) {
        _builder.setPath(value)
      }
    /**
     * ```
     * The path matched by this custom verb.
     * ```
     *
     * `string path = 2;`
     */
    public fun clearPath() {
      _builder.clearPath()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.google.api.CustomHttpPattern.copy(block: `com.google.api`.CustomHttpPatternKt.Dsl.() -> kotlin.Unit): com.google.api.CustomHttpPattern =
  `com.google.api`.CustomHttpPatternKt.Dsl._create(this.toBuilder()).apply { block() }._build()

