// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user_api/v1/user.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package user_api.v1;

@kotlin.jvm.JvmName("-initializeapiKeyEntity")
public inline fun apiKeyEntity(block: user_api.v1.ApiKeyEntityKt.Dsl.() -> kotlin.Unit): user_api.v1.UserOuterClass.ApiKeyEntity =
  user_api.v1.ApiKeyEntityKt.Dsl._create(user_api.v1.UserOuterClass.ApiKeyEntity.newBuilder()).apply { block() }._build()
/**
 * ```
 * [Example]
 * {
 * "client_id": "CLIENT_ID",
 * "client_name": "CLIENT_NAME",
 * "api_key": "API_KEY",
 * "status": 0,
 * "expiry_date": { 
 * "seconds": 0, 
 * "nanos": 0 
 * }
 * }
 * ```
 *
 * Protobuf type `user_api.v1.ApiKeyEntity`
 */
public object ApiKeyEntityKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: user_api.v1.UserOuterClass.ApiKeyEntity.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: user_api.v1.UserOuterClass.ApiKeyEntity.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): user_api.v1.UserOuterClass.ApiKeyEntity = _builder.build()

    /**
     * ```
     * Client ID.
     * ```
     *
     * `string client_id = 1;`
     */
    public var clientId: kotlin.String
      @JvmName("getClientId")
      get() = _builder.getClientId()
      @JvmName("setClientId")
      set(value) {
        _builder.setClientId(value)
      }
    /**
     * ```
     * Client ID.
     * ```
     *
     * `string client_id = 1;`
     */
    public fun clearClientId() {
      _builder.clearClientId()
    }

    /**
     * ```
     * Client Name.
     * ```
     *
     * `string client_name = 2;`
     */
    public var clientName: kotlin.String
      @JvmName("getClientName")
      get() = _builder.getClientName()
      @JvmName("setClientName")
      set(value) {
        _builder.setClientName(value)
      }
    /**
     * ```
     * Client Name.
     * ```
     *
     * `string client_name = 2;`
     */
    public fun clearClientName() {
      _builder.clearClientName()
    }

    /**
     * ```
     * API Key.
     * ```
     *
     * `string api_key = 3;`
     */
    public var apiKey: kotlin.String
      @JvmName("getApiKey")
      get() = _builder.getApiKey()
      @JvmName("setApiKey")
      set(value) {
        _builder.setApiKey(value)
      }
    /**
     * ```
     * API Key.
     * ```
     *
     * `string api_key = 3;`
     */
    public fun clearApiKey() {
      _builder.clearApiKey()
    }

    /**
     * ```
     * API Key Status.
     * ```
     *
     * `.user_api.v1.ApiKeyStatus status = 4;`
     */
    public var status: user_api.v1.UserOuterClass.ApiKeyStatus
      @JvmName("getStatus")
      get() = _builder.getStatus()
      @JvmName("setStatus")
      set(value) {
        _builder.setStatus(value)
      }
    public var statusValue: kotlin.Int
      @JvmName("getStatusValue")
      get() = _builder.getStatusValue()
      @JvmName("setStatusValue")
      set(value) {
        _builder.setStatusValue(value)
      }
    /**
     * ```
     * API Key Status.
     * ```
     *
     * `.user_api.v1.ApiKeyStatus status = 4;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * ```
     * API Key Expiry Timestamp.
     * ```
     *
     * `.google.protobuf.Timestamp expiry_date = 5;`
     */
    public var expiryDate: com.google.protobuf.Timestamp
      @JvmName("getExpiryDate")
      get() = _builder.getExpiryDate()
      @JvmName("setExpiryDate")
      set(value) {
        _builder.setExpiryDate(value)
      }
    /**
     * ```
     * API Key Expiry Timestamp.
     * ```
     *
     * `.google.protobuf.Timestamp expiry_date = 5;`
     */
    public fun clearExpiryDate() {
      _builder.clearExpiryDate()
    }
    /**
     * ```
     * API Key Expiry Timestamp.
     * ```
     *
     * `.google.protobuf.Timestamp expiry_date = 5;`
     * @return Whether the expiryDate field is set.
     */
    public fun hasExpiryDate(): kotlin.Boolean {
      return _builder.hasExpiryDate()
    }
    public val ApiKeyEntityKt.Dsl.expiryDateOrNull: com.google.protobuf.Timestamp?
      get() = _builder.expiryDateOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun user_api.v1.UserOuterClass.ApiKeyEntity.copy(block: `user_api.v1`.ApiKeyEntityKt.Dsl.() -> kotlin.Unit): user_api.v1.UserOuterClass.ApiKeyEntity =
  `user_api.v1`.ApiKeyEntityKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val user_api.v1.UserOuterClass.ApiKeyEntityOrBuilder.expiryDateOrNull: com.google.protobuf.Timestamp?
  get() = if (hasExpiryDate()) getExpiryDate() else null

