// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user_api/v1/user.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package user_api.v1;

@kotlin.jvm.JvmName("-initializeassociateWalletRequest")
public inline fun associateWalletRequest(block: user_api.v1.AssociateWalletRequestKt.Dsl.() -> kotlin.Unit): user_api.v1.UserOuterClass.AssociateWalletRequest =
  user_api.v1.AssociateWalletRequestKt.Dsl._create(user_api.v1.UserOuterClass.AssociateWalletRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * [Example]
 * {
 * "did": "did:method-name:zDIDMultibase58Encoded",
 * "did_type": "DID_TYPE",
 * "purpose": "PURPOSE",
 * "metadata": { 
 * "fields": [
 * {
 * "key": "VALUE"
 * }
 * ]
 * }
 * } 
 * ```
 *
 * Protobuf type `user_api.v1.AssociateWalletRequest`
 */
public object AssociateWalletRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: user_api.v1.UserOuterClass.AssociateWalletRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: user_api.v1.UserOuterClass.AssociateWalletRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): user_api.v1.UserOuterClass.AssociateWalletRequest = _builder.build()

    /**
     * ```
     * W3C Decentralized Identifier (DID) of the wallet to be associated with the account in the bearer token.
     * ```
     *
     * `string did = 1;`
     */
    public var did: kotlin.String
      @JvmName("getDid")
      get() = _builder.getDid()
      @JvmName("setDid")
      set(value) {
        _builder.setDid(value)
      }
    /**
     * ```
     * W3C Decentralized Identifier (DID) of the wallet to be associated with the account in the bearer token.
     * ```
     *
     * `string did = 1;`
     */
    public fun clearDid() {
      _builder.clearDid()
    }

    /**
     * ```
     * Type of DID.
     * ```
     *
     * `string did_type = 2;`
     */
    public var didType: kotlin.String
      @JvmName("getDidType")
      get() = _builder.getDidType()
      @JvmName("setDidType")
      set(value) {
        _builder.setDidType(value)
      }
    /**
     * ```
     * Type of DID.
     * ```
     *
     * `string did_type = 2;`
     */
    public fun clearDidType() {
      _builder.clearDidType()
    }

    /**
     * ```
     * Purpose of the wallet association.
     * ```
     *
     * `string purpose = 3;`
     */
    public var purpose: kotlin.String
      @JvmName("getPurpose")
      get() = _builder.getPurpose()
      @JvmName("setPurpose")
      set(value) {
        _builder.setPurpose(value)
      }
    /**
     * ```
     * Purpose of the wallet association.
     * ```
     *
     * `string purpose = 3;`
     */
    public fun clearPurpose() {
      _builder.clearPurpose()
    }

    /**
     * ```
     * Additional data about the wallet.
     * ```
     *
     * `.google.protobuf.Struct metadata = 12;`
     */
    public var metadata: com.google.protobuf.Struct
      @JvmName("getMetadata")
      get() = _builder.getMetadata()
      @JvmName("setMetadata")
      set(value) {
        _builder.setMetadata(value)
      }
    /**
     * ```
     * Additional data about the wallet.
     * ```
     *
     * `.google.protobuf.Struct metadata = 12;`
     */
    public fun clearMetadata() {
      _builder.clearMetadata()
    }
    /**
     * ```
     * Additional data about the wallet.
     * ```
     *
     * `.google.protobuf.Struct metadata = 12;`
     * @return Whether the metadata field is set.
     */
    public fun hasMetadata(): kotlin.Boolean {
      return _builder.hasMetadata()
    }
    public val AssociateWalletRequestKt.Dsl.metadataOrNull: com.google.protobuf.Struct?
      get() = _builder.metadataOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun user_api.v1.UserOuterClass.AssociateWalletRequest.copy(block: `user_api.v1`.AssociateWalletRequestKt.Dsl.() -> kotlin.Unit): user_api.v1.UserOuterClass.AssociateWalletRequest =
  `user_api.v1`.AssociateWalletRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val user_api.v1.UserOuterClass.AssociateWalletRequestOrBuilder.metadataOrNull: com.google.protobuf.Struct?
  get() = if (hasMetadata()) getMetadata() else null

