// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user_api/v1/user.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package user_api.v1;

@kotlin.jvm.JvmName("-initializesAMLSPMetadataResponse")
public inline fun sAMLSPMetadataResponse(block: user_api.v1.SAMLSPMetadataResponseKt.Dsl.() -> kotlin.Unit): user_api.v1.UserOuterClass.SAMLSPMetadataResponse =
  user_api.v1.SAMLSPMetadataResponseKt.Dsl._create(user_api.v1.UserOuterClass.SAMLSPMetadataResponse.newBuilder()).apply { block() }._build()
/**
 * ```
 * [Example]
 * {
 * "sp_metadata": "SPMetadataVariesLen="
 * }
 * ```
 *
 * Protobuf type `user_api.v1.SAMLSPMetadataResponse`
 */
public object SAMLSPMetadataResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: user_api.v1.UserOuterClass.SAMLSPMetadataResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: user_api.v1.UserOuterClass.SAMLSPMetadataResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): user_api.v1.UserOuterClass.SAMLSPMetadataResponse = _builder.build()

    /**
     * ```
     * Metadata about the service provider using the identity provider.
     * ```
     *
     * `bytes sp_metadata = 1;`
     */
    public var spMetadata: com.google.protobuf.ByteString
      @JvmName("getSpMetadata")
      get() = _builder.getSpMetadata()
      @JvmName("setSpMetadata")
      set(value) {
        _builder.setSpMetadata(value)
      }
    /**
     * ```
     * Metadata about the service provider using the identity provider.
     * ```
     *
     * `bytes sp_metadata = 1;`
     */
    public fun clearSpMetadata() {
      _builder.clearSpMetadata()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun user_api.v1.UserOuterClass.SAMLSPMetadataResponse.copy(block: `user_api.v1`.SAMLSPMetadataResponseKt.Dsl.() -> kotlin.Unit): user_api.v1.UserOuterClass.SAMLSPMetadataResponse =
  `user_api.v1`.SAMLSPMetadataResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

