/* eslint-disable */
/*Generated by GenDocu.com*/
// package: treasury
// file: treasury/v1/treasury.proto

var treasury_v1_treasury_pb = require("../../treasury/v1/treasury_pb");
var grpc = require("@improbable-eng/grpc-web").grpc;

var MonetaeTreasury = (function () {
  function MonetaeTreasury() {}
  MonetaeTreasury.serviceName = "treasury.MonetaeTreasury";
  return MonetaeTreasury;
}());

MonetaeTreasury.Remit = {
  methodName: "Remit",
  service: MonetaeTreasury,
  requestStream: true,
  responseStream: true,
  requestType: treasury_v1_treasury_pb.RemittanceRequest,
  responseType: treasury_v1_treasury_pb.RemittanceResponse
};

MonetaeTreasury.GetSupply = {
  methodName: "GetSupply",
  service: MonetaeTreasury,
  requestStream: false,
  responseStream: false,
  requestType: treasury_v1_treasury_pb.GetSupplyRequest,
  responseType: treasury_v1_treasury_pb.GetSupplyResponse
};

exports.MonetaeTreasury = MonetaeTreasury;

function MonetaeTreasuryClient(serviceHost, options) {
  this.serviceHost = serviceHost;
  this.options = options || {};
}

MonetaeTreasuryClient.prototype.remit = function remit(metadata) {
  var listeners = {
    data: [],
    end: [],
    status: []
  };
  var client = grpc.client(MonetaeTreasury.Remit, {
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport
  });
  client.onEnd(function (status, statusMessage, trailers) {
    listeners.status.forEach(function (handler) {
      handler({ code: status, details: statusMessage, metadata: trailers });
    });
    listeners.end.forEach(function (handler) {
      handler({ code: status, details: statusMessage, metadata: trailers });
    });
    listeners = null;
  });
  client.onMessage(function (message) {
    listeners.data.forEach(function (handler) {
      handler(message);
    })
  });
  client.start(metadata);
  return {
    on: function (type, handler) {
      listeners[type].push(handler);
      return this;
    },
    write: function (requestMessage) {
      client.send(requestMessage);
      return this;
    },
    end: function () {
      client.finishSend();
    },
    cancel: function () {
      listeners = null;
      client.close();
    }
  };
};

MonetaeTreasuryClient.prototype.getSupply = function getSupply(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(MonetaeTreasury.GetSupply, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

exports.MonetaeTreasuryClient = MonetaeTreasuryClient;

