// source: common/v1/packet.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.common.FundsChangeRequest');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.common.Amount');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.common.FundsChangeRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.common.FundsChangeRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.common.FundsChangeRequest.displayName = 'proto.common.FundsChangeRequest';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.common.FundsChangeRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.common.FundsChangeRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.common.FundsChangeRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.common.FundsChangeRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    grossAmount: (f = msg.getGrossAmount()) && proto.common.Amount.toObject(includeInstance, f),
    exactAmount: (f = msg.getExactAmount()) && proto.common.Amount.toObject(includeInstance, f),
    fees: (f = msg.getFees()) && proto.common.Amount.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.common.FundsChangeRequest}
 */
proto.common.FundsChangeRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.common.FundsChangeRequest;
  return proto.common.FundsChangeRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.common.FundsChangeRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.common.FundsChangeRequest}
 */
proto.common.FundsChangeRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.common.Amount;
      reader.readMessage(value,proto.common.Amount.deserializeBinaryFromReader);
      msg.setGrossAmount(value);
      break;
    case 2:
      var value = new proto.common.Amount;
      reader.readMessage(value,proto.common.Amount.deserializeBinaryFromReader);
      msg.setExactAmount(value);
      break;
    case 3:
      var value = new proto.common.Amount;
      reader.readMessage(value,proto.common.Amount.deserializeBinaryFromReader);
      msg.setFees(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.common.FundsChangeRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.common.FundsChangeRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.common.FundsChangeRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.common.FundsChangeRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGrossAmount();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.common.Amount.serializeBinaryToWriter
    );
  }
  f = message.getExactAmount();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.common.Amount.serializeBinaryToWriter
    );
  }
  f = message.getFees();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.common.Amount.serializeBinaryToWriter
    );
  }
};


/**
 * optional Amount gross_amount = 1;
 * @return {?proto.common.Amount}
 */
proto.common.FundsChangeRequest.prototype.getGrossAmount = function() {
  return /** @type{?proto.common.Amount} */ (
    jspb.Message.getWrapperField(this, proto.common.Amount, 1));
};


/**
 * @param {?proto.common.Amount|undefined} value
 * @return {!proto.common.FundsChangeRequest} returns this
*/
proto.common.FundsChangeRequest.prototype.setGrossAmount = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.common.FundsChangeRequest} returns this
 */
proto.common.FundsChangeRequest.prototype.clearGrossAmount = function() {
  return this.setGrossAmount(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.common.FundsChangeRequest.prototype.hasGrossAmount = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Amount exact_amount = 2;
 * @return {?proto.common.Amount}
 */
proto.common.FundsChangeRequest.prototype.getExactAmount = function() {
  return /** @type{?proto.common.Amount} */ (
    jspb.Message.getWrapperField(this, proto.common.Amount, 2));
};


/**
 * @param {?proto.common.Amount|undefined} value
 * @return {!proto.common.FundsChangeRequest} returns this
*/
proto.common.FundsChangeRequest.prototype.setExactAmount = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.common.FundsChangeRequest} returns this
 */
proto.common.FundsChangeRequest.prototype.clearExactAmount = function() {
  return this.setExactAmount(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.common.FundsChangeRequest.prototype.hasExactAmount = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Amount fees = 3;
 * @return {?proto.common.Amount}
 */
proto.common.FundsChangeRequest.prototype.getFees = function() {
  return /** @type{?proto.common.Amount} */ (
    jspb.Message.getWrapperField(this, proto.common.Amount, 3));
};


/**
 * @param {?proto.common.Amount|undefined} value
 * @return {!proto.common.FundsChangeRequest} returns this
*/
proto.common.FundsChangeRequest.prototype.setFees = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.common.FundsChangeRequest} returns this
 */
proto.common.FundsChangeRequest.prototype.clearFees = function() {
  return this.setFees(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.common.FundsChangeRequest.prototype.hasFees = function() {
  return jspb.Message.getField(this, 3) != null;
};


