// source: common/v1/packet.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.common.PacketType');

/**
 * @enum {number}
 */
proto.common.PacketType = {
  UNKNOWN: 0,
  UNSUPPORTED: 1,
  AUTHENTICATE: 2,
  CONNECTIONAUTHENTICATED: 7,
  RETURNTOSENDER: 3,
  TERMINATESTREAM: 4,
  KEEPALIVE: 5,
  ACKNOWLEDGEMENT: 6,
  ADDASSOCIATEDCONNECTION: 9,
  DROPASSOCIATEDCONNECTION: 10,
  ASSOCIATEDCONNECTIONADDED: 11,
  ASSOCIATEDCONNECTIONDROPPED: 12,
  REPORT: 50,
  PROMISSORY: 100,
  AUTHORIZEPROMISSORY: 101,
  AUTHORIZEANDFORWARDPROMISSORY: 102,
  ARCHIVEPROMISSORY: 103,
  PROMISSORYRECEIPT: 104,
  AUTHORIZATIONSTATUS: 108,
  RETRIEVEASSETS: 109,
  PROMISSORYBATCH: 110,
  LOCKPROMISSORYBATCH: 111,
  LOCKPROMISSORYBATCHACK: 112,
  RETRIEVEASSETSBATCH: 113,
  AUTHORIZEANDFORWARDPROMISSORYBATCH: 116,
  VALIDATIONBLOCKBATCH: 117,
  AUTHORIZEDBLOCKBATCH: 118,
  MINTPROMISSORY: 119,
  FRESHPROMISSORYBATCH: 120,
  MINTEDPROMISSORYBATCH: 121,
  REDEEMVALIDATIONBLOCKBATCH: 122,
  IDENTITYREQUEST: 200,
  IDENTITYRESPONSE: 201,
  IDENTITYPROOF: 202,
  AUTHORIZATIONFAILED: 300,
  EMISSARYCONNECTIONIDENTITY: 400,
  CONTRACTPROPOSAL: 500,
  CONTRACTPROPOSALACK: 501,
  CONTRACTPROPOSALNACK: 502,
  CONTRACTSIGNATURE: 503,
  CONTRACTCOMPLETE: 504,
  RECOVERYDATA: 600,
  REMITTANCEREQUEST: 700,
  REMITTANCERESPONSE: 701,
  TXNCONTRACT: 1303,
  TXNCONTRACTACK: 1304,
  TXNASSETSAUTHORIZED: 1305,
  TXNSECRETREQUEST: 1308,
  TXNSECRETPRESENT: 1309,
  TXNASSETSRETURNED: 1310,
  TXNRECOVER: 1311
};

