// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: emissary_api/v1/emissary.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Emissary {
  /// <summary>
  /// MonetaeEmissary service is empty but still needed for health probes.
  /// </summary>
  public static partial class MonetaeEmissary
  {
    static readonly string __ServiceName = "emissary.MonetaeEmissary";


    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Emissary.EmissaryReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of MonetaeEmissary</summary>
    [grpc::BindServiceMethod(typeof(MonetaeEmissary), "BindService")]
    public abstract partial class MonetaeEmissaryBase
    {
    }

    /// <summary>Client for MonetaeEmissary</summary>
    public partial class MonetaeEmissaryClient : grpc::ClientBase<MonetaeEmissaryClient>
    {
      /// <summary>Creates a new client for MonetaeEmissary</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public MonetaeEmissaryClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for MonetaeEmissary that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public MonetaeEmissaryClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected MonetaeEmissaryClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected MonetaeEmissaryClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override MonetaeEmissaryClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new MonetaeEmissaryClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(MonetaeEmissaryBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder().Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, MonetaeEmissaryBase serviceImpl)
    {
    }

  }
}
#endregion
