// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: webhook_api/v1/webhook.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package webhook_api.v1;

@kotlin.jvm.JvmName("-initializecreateScheduledReactionRequest")
public inline fun createScheduledReactionRequest(block: webhook_api.v1.CreateScheduledReactionRequestKt.Dsl.() -> kotlin.Unit): webhook_api.v1.WebhookOuterClass.CreateScheduledReactionRequest =
  webhook_api.v1.CreateScheduledReactionRequestKt.Dsl._create(webhook_api.v1.WebhookOuterClass.CreateScheduledReactionRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * [Example]
 * {
 * "api_key": "API_KEY",
 * "name": "REACTION_NAME1",
 * "reaction_type": 1,
 * "cron_tab": "*****",
 * "reaction_payload": {
 * "create_contract_payload": {
 * "sender_wallet_id": "SENDER_WALLET_ID1",
 * "commitments": [
 * {
 * "sender": "zSenderPublicKey",
 * "recipient": "zRecipientPublicKey",
 * "amount": {
 * "currency_code":"USD",
 * "amount":100,
 * "decimals":2
 * }
 * },
 * {
 * "sender": "zSenderPublicKey2",
 * "recipient": "zRecipientPublicKey2",
 * "amount": {
 * "currency_code":"USD",
 * "amount":500,
 * "decimals":2
 * }
 * }
 * ],
 * "conditions": [
 * {
 * "condition": {
 * "hash": {
 * "presenter": "PresenterPublicKey",
 * "hash": "13550350a8681c84"
 * }
 * }
 * },
 * {
 * "condition": {
 * "hash": {
 * "presenter": "PresenterPublicKey",
 * "hash": "13550350a8681c84"
 * }
 * }
 * }
 * ],
 * "timeout_secs": 10000,
 * "memo": "MEMO"
 * }
 * }
 * }
 * ```
 *
 * Protobuf type `webhook_api.v1.CreateScheduledReactionRequest`
 */
public object CreateScheduledReactionRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: webhook_api.v1.WebhookOuterClass.CreateScheduledReactionRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: webhook_api.v1.WebhookOuterClass.CreateScheduledReactionRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): webhook_api.v1.WebhookOuterClass.CreateScheduledReactionRequest = _builder.build()

    /**
     * ```
     * API Key as a JWT
     * ```
     *
     * `string api_key = 1;`
     */
    public var apiKey: kotlin.String
      @JvmName("getApiKey")
      get() = _builder.getApiKey()
      @JvmName("setApiKey")
      set(value) {
        _builder.setApiKey(value)
      }
    /**
     * ```
     * API Key as a JWT
     * ```
     *
     * `string api_key = 1;`
     */
    public fun clearApiKey() {
      _builder.clearApiKey()
    }

    /**
     * ```
     * Webhook name.
     * ```
     *
     * `string name = 2;`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * ```
     * Webhook name.
     * ```
     *
     * `string name = 2;`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * ```
     * Reaction type.
     * ```
     *
     * `.webhook_api.v1.ScheduleReactionType reaction_type = 3;`
     */
    public var reactionType: webhook_api.v1.WebhookOuterClass.ScheduleReactionType
      @JvmName("getReactionType")
      get() = _builder.getReactionType()
      @JvmName("setReactionType")
      set(value) {
        _builder.setReactionType(value)
      }
    public var reactionTypeValue: kotlin.Int
      @JvmName("getReactionTypeValue")
      get() = _builder.getReactionTypeValue()
      @JvmName("setReactionTypeValue")
      set(value) {
        _builder.setReactionTypeValue(value)
      }
    /**
     * ```
     * Reaction type.
     * ```
     *
     * `.webhook_api.v1.ScheduleReactionType reaction_type = 3;`
     */
    public fun clearReactionType() {
      _builder.clearReactionType()
    }

    /**
     * ```
     *
     * Recurring schedule in the form of a crontab string
     * Expects exactly five digit chars in the string.
     * The example below runs once a minute:
     * ┌───────────── minute (0 - 59)
     * │ ┌───────────── hour (0 - 23)
     * │ │ ┌───────────── day of the month (1 - 31)
     * │ │ │ ┌───────────── month (1 - 12)
     * │ │ │ │ ┌───────────── day of the week (0 - 6) (Sunday to Saturday)
     * │ │ │ │ │
     * │ │ │ │ │
     * │ │ │ │ │
     * * * * *
     * ```
     *
     * `string cron_tab = 4;`
     */
    public var cronTab: kotlin.String
      @JvmName("getCronTab")
      get() = _builder.getCronTab()
      @JvmName("setCronTab")
      set(value) {
        _builder.setCronTab(value)
      }
    /**
     * ```
     *
     * Recurring schedule in the form of a crontab string
     * Expects exactly five digit chars in the string.
     * The example below runs once a minute:
     * ┌───────────── minute (0 - 59)
     * │ ┌───────────── hour (0 - 23)
     * │ │ ┌───────────── day of the month (1 - 31)
     * │ │ │ ┌───────────── month (1 - 12)
     * │ │ │ │ ┌───────────── day of the week (0 - 6) (Sunday to Saturday)
     * │ │ │ │ │
     * │ │ │ │ │
     * │ │ │ │ │
     * * * * *
     * ```
     *
     * `string cron_tab = 4;`
     */
    public fun clearCronTab() {
      _builder.clearCronTab()
    }

    /**
     * ```
     * Reaction Payload for sending payment.
     * ```
     *
     * `.webhook_api.v1.CreateContractReactionPayload create_contract_payload = 5;`
     */
    public var createContractPayload: webhook_api.v1.WebhookOuterClass.CreateContractReactionPayload
      @JvmName("getCreateContractPayload")
      get() = _builder.getCreateContractPayload()
      @JvmName("setCreateContractPayload")
      set(value) {
        _builder.setCreateContractPayload(value)
      }
    /**
     * ```
     * Reaction Payload for sending payment.
     * ```
     *
     * `.webhook_api.v1.CreateContractReactionPayload create_contract_payload = 5;`
     */
    public fun clearCreateContractPayload() {
      _builder.clearCreateContractPayload()
    }
    /**
     * ```
     * Reaction Payload for sending payment.
     * ```
     *
     * `.webhook_api.v1.CreateContractReactionPayload create_contract_payload = 5;`
     * @return Whether the createContractPayload field is set.
     */
    public fun hasCreateContractPayload(): kotlin.Boolean {
      return _builder.hasCreateContractPayload()
    }
    public val reactionPayloadCase: webhook_api.v1.WebhookOuterClass.CreateScheduledReactionRequest.ReactionPayloadCase
      @JvmName("getReactionPayloadCase")
      get() = _builder.getReactionPayloadCase()

    public fun clearReactionPayload() {
      _builder.clearReactionPayload()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun webhook_api.v1.WebhookOuterClass.CreateScheduledReactionRequest.copy(block: `webhook_api.v1`.CreateScheduledReactionRequestKt.Dsl.() -> kotlin.Unit): webhook_api.v1.WebhookOuterClass.CreateScheduledReactionRequest =
  `webhook_api.v1`.CreateScheduledReactionRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val webhook_api.v1.WebhookOuterClass.CreateScheduledReactionRequestOrBuilder.createContractPayloadOrNull: webhook_api.v1.WebhookOuterClass.CreateContractReactionPayload?
  get() = if (hasCreateContractPayload()) getCreateContractPayload() else null

