// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/v1/packet.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package common;

@kotlin.jvm.JvmName("-initializefundsChangeAck")
public inline fun fundsChangeAck(block: common.FundsChangeAckKt.Dsl.() -> kotlin.Unit): common.PacketOuterClass.FundsChangeAck =
  common.FundsChangeAckKt.Dsl._create(common.PacketOuterClass.FundsChangeAck.newBuilder()).apply { block() }._build()
/**
 * ```
 * [Example]
 * {}
 * ```
 *
 * Protobuf type `common.FundsChangeAck`
 */
public object FundsChangeAckKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: common.PacketOuterClass.FundsChangeAck.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: common.PacketOuterClass.FundsChangeAck.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): common.PacketOuterClass.FundsChangeAck = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun common.PacketOuterClass.FundsChangeAck.copy(block: `common`.FundsChangeAckKt.Dsl.() -> kotlin.Unit): common.PacketOuterClass.FundsChangeAck =
  `common`.FundsChangeAckKt.Dsl._create(this.toBuilder()).apply { block() }._build()

