// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/v1/packet.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package common;

@kotlin.jvm.JvmName("-initializefundsChangeRequest")
public inline fun fundsChangeRequest(block: common.FundsChangeRequestKt.Dsl.() -> kotlin.Unit): common.PacketOuterClass.FundsChangeRequest =
  common.FundsChangeRequestKt.Dsl._create(common.PacketOuterClass.FundsChangeRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * [Example]
 * {
 * "gross_amount": {
 * "currency_code":"USD",
 * "amount":500,
 * "decimals":2
 * },
 * "exact_amount": {
 * "currency_code":"USD",
 * "amount":499,
 * "decimals":2
 * },
 * "fees": {
 * "currency_code":"USD",
 * "amount":1,
 * "decimals":2
 * }
 * }
 * ```
 *
 * Protobuf type `common.FundsChangeRequest`
 */
public object FundsChangeRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: common.PacketOuterClass.FundsChangeRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: common.PacketOuterClass.FundsChangeRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): common.PacketOuterClass.FundsChangeRequest = _builder.build()

    /**
     * ```
     * Gross Amount Requested
     * ```
     *
     * `.common.Amount gross_amount = 1;`
     */
    public var grossAmount: common.Common.Amount
      @JvmName("getGrossAmount")
      get() = _builder.getGrossAmount()
      @JvmName("setGrossAmount")
      set(value) {
        _builder.setGrossAmount(value)
      }
    /**
     * ```
     * Gross Amount Requested
     * ```
     *
     * `.common.Amount gross_amount = 1;`
     */
    public fun clearGrossAmount() {
      _builder.clearGrossAmount()
    }
    /**
     * ```
     * Gross Amount Requested
     * ```
     *
     * `.common.Amount gross_amount = 1;`
     * @return Whether the grossAmount field is set.
     */
    public fun hasGrossAmount(): kotlin.Boolean {
      return _builder.hasGrossAmount()
    }
    public val FundsChangeRequestKt.Dsl.grossAmountOrNull: common.Common.Amount?
      get() = _builder.grossAmountOrNull

    /**
     * ```
     * Exact Amount Requested
     * ```
     *
     * `.common.Amount exact_amount = 2;`
     */
    public var exactAmount: common.Common.Amount
      @JvmName("getExactAmount")
      get() = _builder.getExactAmount()
      @JvmName("setExactAmount")
      set(value) {
        _builder.setExactAmount(value)
      }
    /**
     * ```
     * Exact Amount Requested
     * ```
     *
     * `.common.Amount exact_amount = 2;`
     */
    public fun clearExactAmount() {
      _builder.clearExactAmount()
    }
    /**
     * ```
     * Exact Amount Requested
     * ```
     *
     * `.common.Amount exact_amount = 2;`
     * @return Whether the exactAmount field is set.
     */
    public fun hasExactAmount(): kotlin.Boolean {
      return _builder.hasExactAmount()
    }
    public val FundsChangeRequestKt.Dsl.exactAmountOrNull: common.Common.Amount?
      get() = _builder.exactAmountOrNull

    /**
     * ```
     * Fees
     * ```
     *
     * `.common.Amount fees = 3;`
     */
    public var fees: common.Common.Amount
      @JvmName("getFees")
      get() = _builder.getFees()
      @JvmName("setFees")
      set(value) {
        _builder.setFees(value)
      }
    /**
     * ```
     * Fees
     * ```
     *
     * `.common.Amount fees = 3;`
     */
    public fun clearFees() {
      _builder.clearFees()
    }
    /**
     * ```
     * Fees
     * ```
     *
     * `.common.Amount fees = 3;`
     * @return Whether the fees field is set.
     */
    public fun hasFees(): kotlin.Boolean {
      return _builder.hasFees()
    }
    public val FundsChangeRequestKt.Dsl.feesOrNull: common.Common.Amount?
      get() = _builder.feesOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun common.PacketOuterClass.FundsChangeRequest.copy(block: `common`.FundsChangeRequestKt.Dsl.() -> kotlin.Unit): common.PacketOuterClass.FundsChangeRequest =
  `common`.FundsChangeRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val common.PacketOuterClass.FundsChangeRequestOrBuilder.grossAmountOrNull: common.Common.Amount?
  get() = if (hasGrossAmount()) getGrossAmount() else null

public val common.PacketOuterClass.FundsChangeRequestOrBuilder.exactAmountOrNull: common.Common.Amount?
  get() = if (hasExactAmount()) getExactAmount() else null

public val common.PacketOuterClass.FundsChangeRequestOrBuilder.feesOrNull: common.Common.Amount?
  get() = if (hasFees()) getFees() else null

