// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/v1/common.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package common;

@kotlin.jvm.JvmName("-initializegetServiceTypeRequest")
public inline fun getServiceTypeRequest(block: common.GetServiceTypeRequestKt.Dsl.() -> kotlin.Unit): common.Common.GetServiceTypeRequest =
  common.GetServiceTypeRequestKt.Dsl._create(common.Common.GetServiceTypeRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * [Example]
 * {}
 * ```
 *
 * Protobuf type `common.GetServiceTypeRequest`
 */
public object GetServiceTypeRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: common.Common.GetServiceTypeRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: common.Common.GetServiceTypeRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): common.Common.GetServiceTypeRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun common.Common.GetServiceTypeRequest.copy(block: `common`.GetServiceTypeRequestKt.Dsl.() -> kotlin.Unit): common.Common.GetServiceTypeRequest =
  `common`.GetServiceTypeRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

