// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: common/v1/amqp.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Payload Type, subject to change.
type PayloadType int32

const (
	// New Transaction payload, subject to change.
	PayloadType_NewTransaction PayloadType = 0
	// Ack Proposal payload, subject to change.
	PayloadType_AckProposal PayloadType = 1
	// Acked Proposal payload, subject to change.
	PayloadType_ProposalAcked PayloadType = 2
	// Nacked Proposal payload, subject to change.
	PayloadType_ProposalNacked PayloadType = 3
	// Reveal Secret payload, subject to change.
	PayloadType_RevealSecret PayloadType = 4
	// Revealed Secret payload, subject to change.
	PayloadType_SecretRevealed PayloadType = 5
	// Received Secret payload, subject to change.
	PayloadType_ReceiveSecret PayloadType = 6
	// Received Termination payload, subject to change.
	PayloadType_ReceiveTermination PayloadType = 7
)

// Enum value maps for PayloadType.
var (
	PayloadType_name = map[int32]string{
		0: "NewTransaction",
		1: "AckProposal",
		2: "ProposalAcked",
		3: "ProposalNacked",
		4: "RevealSecret",
		5: "SecretRevealed",
		6: "ReceiveSecret",
		7: "ReceiveTermination",
	}
	PayloadType_value = map[string]int32{
		"NewTransaction":     0,
		"AckProposal":        1,
		"ProposalAcked":      2,
		"ProposalNacked":     3,
		"RevealSecret":       4,
		"SecretRevealed":     5,
		"ReceiveSecret":      6,
		"ReceiveTermination": 7,
	}
)

func (x PayloadType) Enum() *PayloadType {
	p := new(PayloadType)
	*p = x
	return p
}

func (x PayloadType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayloadType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_amqp_proto_enumTypes[0].Descriptor()
}

func (PayloadType) Type() protoreflect.EnumType {
	return &file_common_v1_amqp_proto_enumTypes[0]
}

func (x PayloadType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayloadType.Descriptor instead.
func (PayloadType) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_amqp_proto_rawDescGZIP(), []int{0}
}

// Termination Result, subject to change.
type TerminationResult int32

const (
	// Contract Failed, subject to change.
	TerminationResult_ContractFailed TerminationResult = 0
	// Transaction Failed, subject to change.
	TerminationResult_TxnFailed TerminationResult = 1
	// Transaction Completed, subject to change.
	TerminationResult_TxnCompleted TerminationResult = 2
)

// Enum value maps for TerminationResult.
var (
	TerminationResult_name = map[int32]string{
		0: "ContractFailed",
		1: "TxnFailed",
		2: "TxnCompleted",
	}
	TerminationResult_value = map[string]int32{
		"ContractFailed": 0,
		"TxnFailed":      1,
		"TxnCompleted":   2,
	}
)

func (x TerminationResult) Enum() *TerminationResult {
	p := new(TerminationResult)
	*p = x
	return p
}

func (x TerminationResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TerminationResult) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_amqp_proto_enumTypes[1].Descriptor()
}

func (TerminationResult) Type() protoreflect.EnumType {
	return &file_common_v1_amqp_proto_enumTypes[1]
}

func (x TerminationResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TerminationResult.Descriptor instead.
func (TerminationResult) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_amqp_proto_rawDescGZIP(), []int{1}
}

// [Example]
// {
// "payload_type": 1,
// "data": "xDATAxBYTES="
// }
type Payload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Payload type.
	PayloadType PayloadType `protobuf:"varint,1,opt,name=payload_type,json=payloadType,proto3,enum=common.PayloadType" json:"payload_type,omitempty"`
	// Payload data.
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Payload) Reset() {
	*x = Payload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_amqp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_amqp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_common_v1_amqp_proto_rawDescGZIP(), []int{0}
}

func (x *Payload) GetPayloadType() PayloadType {
	if x != nil {
		return x.PayloadType
	}
	return PayloadType_NewTransaction
}

func (x *Payload) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// {
// "contract": {
// "urn": "urn:knox:swap:001",
// "id": "CONTRACT_ID",
// "commitments": [
// {
// "sender": "zSender1PublicKey",
// "recipient": "zRecipient1PublicKey",
// "amount": {
// "currency_code":"USD",
// "amount":100,
// "decimals":2
// }
// },
// {
// "sender": "zSender2PublicKey",
// "recipient": "zRecipient2PublicKey",
// "amount": {
// "currency_code":"USD",
// "amount":100,
// "decimals":2
// }
// }
// ],
// "conditions": [
// {
// "condition": {
// "timeout": 1687180000
// }
// }
// ],
// "signatories": {
// "Key1": "BYTES=",
// "Key2": "BYTES="
// },
// "memo": "AtomicAssetSwap"
// },
// "owner": "zOwnerPublicKey"
// }
type NewTransactionData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Contract.
	Contract *Contract `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	// Owner Public Key.
	Owner string `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (x *NewTransactionData) Reset() {
	*x = NewTransactionData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_amqp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewTransactionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewTransactionData) ProtoMessage() {}

func (x *NewTransactionData) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_amqp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewTransactionData.ProtoReflect.Descriptor instead.
func (*NewTransactionData) Descriptor() ([]byte, []int) {
	return file_common_v1_amqp_proto_rawDescGZIP(), []int{1}
}

func (x *NewTransactionData) GetContract() *Contract {
	if x != nil {
		return x.Contract
	}
	return nil
}

func (x *NewTransactionData) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

// {
// "contract": {
// "urn": "urn:knox:swap:001",
// "id": "CONTRACT_ID",
// "commitments": [
// {
// "sender": "zSender1PublicKey",
// "recipient": "zRecipient1PublicKey",
// "amount": {
// "currency_code":"USD",
// "amount":100,
// "decimals":2
// }
// },
// {
// "sender": "zSender2PublicKey",
// "recipient": "zRecipient2PublicKey",
// "amount": {
// "currency_code":"USD",
// "amount":100,
// "decimals":2
// }
// }
// ],
// "conditions": [
// {
// "condition": {
// "timeout": 1687180000
// }
// }
// ],
// "signatories": {
// "Key1": "BYTES=",
// "Key2": "BYTES="
// },
// "memo": "AtomicAssetSwap"
// },
// "owner": "zOwnerPublicKey",
// "originator": "zOriginatorPublicKey"
// }
type AckProposalData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Contract.
	Contract *Contract `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	// Owner Public Key.
	Owner string `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	// Originator Public Key.
	Originator string `protobuf:"bytes,3,opt,name=originator,proto3" json:"originator,omitempty"`
}

func (x *AckProposalData) Reset() {
	*x = AckProposalData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_amqp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AckProposalData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckProposalData) ProtoMessage() {}

func (x *AckProposalData) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_amqp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckProposalData.ProtoReflect.Descriptor instead.
func (*AckProposalData) Descriptor() ([]byte, []int) {
	return file_common_v1_amqp_proto_rawDescGZIP(), []int{2}
}

func (x *AckProposalData) GetContract() *Contract {
	if x != nil {
		return x.Contract
	}
	return nil
}

func (x *AckProposalData) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *AckProposalData) GetOriginator() string {
	if x != nil {
		return x.Originator
	}
	return ""
}

// {
// "owner": "zOwnerPublicKey",
// "originator": "zOriginatorPublicKey",
// "contract": {
// "urn": "urn:knox:swap:001",
// "id": "CONTRACT_ID",
// "commitments": [
// {
// "sender": "zSender1PublicKey",
// "recipient": "zRecipient1PublicKey",
// "amount": {
// "currency_code":"USD",
// "amount":100,
// "decimals":2
// }
// },
// {
// "sender": "zSender2PublicKey",
// "recipient": "zRecipient2PublicKey",
// "amount": {
// "currency_code":"USD",
// "amount":100,
// "decimals":2
// }
// }
// ],
// "conditions": [
// {
// "condition": {
// "timeout": 1687180000
// }
// }
// ],
// "signatories": {
// "Key1": "BYTES=",
// "Key2": "BYTES="
// },
// "memo": "AtomicAssetSwap"
// }
// }
type ProposalAckNackData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Owner Public Key.
	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	// Originator Public Key.
	Originator string `protobuf:"bytes,2,opt,name=originator,proto3" json:"originator,omitempty"`
	// Contract.
	Contract *Contract `protobuf:"bytes,3,opt,name=contract,proto3" json:"contract,omitempty"`
}

func (x *ProposalAckNackData) Reset() {
	*x = ProposalAckNackData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_amqp_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProposalAckNackData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalAckNackData) ProtoMessage() {}

func (x *ProposalAckNackData) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_amqp_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalAckNackData.ProtoReflect.Descriptor instead.
func (*ProposalAckNackData) Descriptor() ([]byte, []int) {
	return file_common_v1_amqp_proto_rawDescGZIP(), []int{3}
}

func (x *ProposalAckNackData) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *ProposalAckNackData) GetOriginator() string {
	if x != nil {
		return x.Originator
	}
	return ""
}

func (x *ProposalAckNackData) GetContract() *Contract {
	if x != nil {
		return x.Contract
	}
	return nil
}

// [Example]
// {
// "contract_id": "a18f7224-a7c1-41f8-b14f-75e920b8ea81",
// "owner": "zOwnerPublicKey"
// }
type RevealSecretData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Contract ID.
	ContractId string `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	// Owner Public Key.
	Owner string `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (x *RevealSecretData) Reset() {
	*x = RevealSecretData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_amqp_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevealSecretData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevealSecretData) ProtoMessage() {}

func (x *RevealSecretData) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_amqp_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevealSecretData.ProtoReflect.Descriptor instead.
func (*RevealSecretData) Descriptor() ([]byte, []int) {
	return file_common_v1_amqp_proto_rawDescGZIP(), []int{4}
}

func (x *RevealSecretData) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *RevealSecretData) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

// [Example]
// {
// "owner": "zOwnerPublicKey",
// "contract_id": "a18f7224-a7c1-41f8-b14f-75e920b8ea81",
// "secret": "SecretBytes"
// }
type SecretRevealedData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Owner Public Key.
	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	// Contract ID.
	ContractId string `protobuf:"bytes,2,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	// Base64 Encoding of Secret bytes.
	Secret string `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
}

func (x *SecretRevealedData) Reset() {
	*x = SecretRevealedData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_amqp_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecretRevealedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretRevealedData) ProtoMessage() {}

func (x *SecretRevealedData) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_amqp_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretRevealedData.ProtoReflect.Descriptor instead.
func (*SecretRevealedData) Descriptor() ([]byte, []int) {
	return file_common_v1_amqp_proto_rawDescGZIP(), []int{5}
}

func (x *SecretRevealedData) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *SecretRevealedData) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *SecretRevealedData) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

// [Example]
// {
// "contract_id": "a18f7224-a7c1-41f8-b14f-75e920b8ea81",
// "owner": "zOwnerPublicKey",
// "secret": "SecretBytes"
// }
type ReceiveSecretData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Contract ID.
	ContractId string `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	// Owner Public Key.
	Owner string `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	// Base64 Encoding of Secret bytes.
	Secret string `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
}

func (x *ReceiveSecretData) Reset() {
	*x = ReceiveSecretData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_amqp_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceiveSecretData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveSecretData) ProtoMessage() {}

func (x *ReceiveSecretData) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_amqp_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveSecretData.ProtoReflect.Descriptor instead.
func (*ReceiveSecretData) Descriptor() ([]byte, []int) {
	return file_common_v1_amqp_proto_rawDescGZIP(), []int{6}
}

func (x *ReceiveSecretData) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *ReceiveSecretData) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *ReceiveSecretData) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

// [Example]
// {
// "contract_id": "a18f7224-a7c1-41f8-b14f-75e920b8ea81",
// "owner": "zOwnerPublicKey",
// "result": "Completed"
// }
type ReceiveTerminationData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Contract ID.
	ContractId string `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	// Owner Public Key.
	Owner string `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	// Result.
	Result TerminationResult `protobuf:"varint,3,opt,name=result,proto3,enum=common.TerminationResult" json:"result,omitempty"`
}

func (x *ReceiveTerminationData) Reset() {
	*x = ReceiveTerminationData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_amqp_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceiveTerminationData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveTerminationData) ProtoMessage() {}

func (x *ReceiveTerminationData) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_amqp_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveTerminationData.ProtoReflect.Descriptor instead.
func (*ReceiveTerminationData) Descriptor() ([]byte, []int) {
	return file_common_v1_amqp_proto_rawDescGZIP(), []int{7}
}

func (x *ReceiveTerminationData) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *ReceiveTerminationData) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *ReceiveTerminationData) GetResult() TerminationResult {
	if x != nil {
		return x.Result
	}
	return TerminationResult_ContractFailed
}

var File_common_v1_amqp_proto protoreflect.FileDescriptor

var file_common_v1_amqp_proto_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x6d, 0x71, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x1a, 0x16,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x55, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x12, 0x36, 0x0a, 0x0c, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x58, 0x0a,
	0x12, 0x4e, 0x65, 0x77, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x2c, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x22, 0x75, 0x0a, 0x0f, 0x41, 0x63, 0x6b, 0x50, 0x72,
	0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2c, 0x0a, 0x08, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x08,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x1e,
	0x0a, 0x0a, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x79,
	0x0a, 0x13, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x41, 0x63, 0x6b, 0x4e, 0x61, 0x63,
	0x6b, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x6f,
	0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x2c, 0x0a, 0x08, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52,
	0x08, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x22, 0x49, 0x0a, 0x10, 0x52, 0x65, 0x76,
	0x65, 0x61, 0x6c, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1f, 0x0a,
	0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f,
	0x77, 0x6e, 0x65, 0x72, 0x22, 0x63, 0x0a, 0x12, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x65,
	0x76, 0x65, 0x61, 0x6c, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77,
	0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72,
	0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x22, 0x62, 0x0a, 0x11, 0x52, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1f,
	0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x22, 0x82, 0x01,
	0x0a, 0x16, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12,
	0x31, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x19, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x2a, 0xaa, 0x01, 0x0a, 0x0b, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x12, 0x0a, 0x0e, 0x4e, 0x65, 0x77, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x63, 0x6b, 0x50, 0x72, 0x6f,
	0x70, 0x6f, 0x73, 0x61, 0x6c, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x70, 0x6f,
	0x73, 0x61, 0x6c, 0x41, 0x63, 0x6b, 0x65, 0x64, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x50, 0x72,
	0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x4e, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x10, 0x03, 0x12, 0x10,
	0x0a, 0x0c, 0x52, 0x65, 0x76, 0x65, 0x61, 0x6c, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x10, 0x04,
	0x12, 0x12, 0x0a, 0x0e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x65, 0x76, 0x65, 0x61, 0x6c,
	0x65, 0x64, 0x10, 0x05, 0x12, 0x11, 0x0a, 0x0d, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x53,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x10, 0x06, 0x12, 0x16, 0x0a, 0x12, 0x52, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x10, 0x07, 0x2a,
	0x48, 0x0a, 0x11, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x78, 0x6e, 0x46,
	0x61, 0x69, 0x6c, 0x65, 0x64, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x54, 0x78, 0x6e, 0x43, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x10, 0x02, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x6e, 0x6f, 0x78, 0x2d, 0x6e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x73, 0x64, 0x6b, 0x73, 0x2f,
	0x73, 0x64, 0x6b, 0x2f, 0x67, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_v1_amqp_proto_rawDescOnce sync.Once
	file_common_v1_amqp_proto_rawDescData = file_common_v1_amqp_proto_rawDesc
)

func file_common_v1_amqp_proto_rawDescGZIP() []byte {
	file_common_v1_amqp_proto_rawDescOnce.Do(func() {
		file_common_v1_amqp_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_v1_amqp_proto_rawDescData)
	})
	return file_common_v1_amqp_proto_rawDescData
}

var file_common_v1_amqp_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_common_v1_amqp_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_common_v1_amqp_proto_goTypes = []interface{}{
	(PayloadType)(0),               // 0: common.PayloadType
	(TerminationResult)(0),         // 1: common.TerminationResult
	(*Payload)(nil),                // 2: common.Payload
	(*NewTransactionData)(nil),     // 3: common.NewTransactionData
	(*AckProposalData)(nil),        // 4: common.AckProposalData
	(*ProposalAckNackData)(nil),    // 5: common.ProposalAckNackData
	(*RevealSecretData)(nil),       // 6: common.RevealSecretData
	(*SecretRevealedData)(nil),     // 7: common.SecretRevealedData
	(*ReceiveSecretData)(nil),      // 8: common.ReceiveSecretData
	(*ReceiveTerminationData)(nil), // 9: common.ReceiveTerminationData
	(*Contract)(nil),               // 10: common.Contract
}
var file_common_v1_amqp_proto_depIdxs = []int32{
	0,  // 0: common.Payload.payload_type:type_name -> common.PayloadType
	10, // 1: common.NewTransactionData.contract:type_name -> common.Contract
	10, // 2: common.AckProposalData.contract:type_name -> common.Contract
	10, // 3: common.ProposalAckNackData.contract:type_name -> common.Contract
	1,  // 4: common.ReceiveTerminationData.result:type_name -> common.TerminationResult
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_common_v1_amqp_proto_init() }
func file_common_v1_amqp_proto_init() {
	if File_common_v1_amqp_proto != nil {
		return
	}
	file_common_v1_packet_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_common_v1_amqp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Payload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_v1_amqp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewTransactionData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_v1_amqp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AckProposalData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_v1_amqp_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProposalAckNackData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_v1_amqp_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RevealSecretData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_v1_amqp_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecretRevealedData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_v1_amqp_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceiveSecretData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_v1_amqp_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceiveTerminationData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_v1_amqp_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_amqp_proto_goTypes,
		DependencyIndexes: file_common_v1_amqp_proto_depIdxs,
		EnumInfos:         file_common_v1_amqp_proto_enumTypes,
		MessageInfos:      file_common_v1_amqp_proto_msgTypes,
	}.Build()
	File_common_v1_amqp_proto = out.File
	file_common_v1_amqp_proto_rawDesc = nil
	file_common_v1_amqp_proto_goTypes = nil
	file_common_v1_amqp_proto_depIdxs = nil
}
