/* eslint-disable */
/*Generated by GenDocu.com*/
// package: transaction_manager
// file: transaction_manager_api/v1/transaction_manager.proto

var transaction_manager_api_v1_transaction_manager_pb = require("../../transaction_manager_api/v1/transaction_manager_pb");
var grpc = require("@improbable-eng/grpc-web").grpc;

var TransactionManager = (function () {
  function TransactionManager() {}
  TransactionManager.serviceName = "transaction_manager.TransactionManager";
  return TransactionManager;
}());

exports.TransactionManager = TransactionManager;

function TransactionManagerClient(serviceHost, options) {
  this.serviceHost = serviceHost;
  this.options = options || {};
}

exports.TransactionManagerClient = TransactionManagerClient;

