// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.1
// source: wallet_api/v1/wallet.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	WalletService_CreateOwner_FullMethodName                           = "/wallet_api.v1.WalletService/CreateOwner"
	WalletService_CreateWallet_FullMethodName                          = "/wallet_api.v1.WalletService/CreateWallet"
	WalletService_ListWallets_FullMethodName                           = "/wallet_api.v1.WalletService/ListWallets"
	WalletService_ListAssetFiles_FullMethodName                        = "/wallet_api.v1.WalletService/ListAssetFiles"
	WalletService_ListWalletBalances_FullMethodName                    = "/wallet_api.v1.WalletService/ListWalletBalances"
	WalletService_ListCredentials_FullMethodName                       = "/wallet_api.v1.WalletService/ListCredentials"
	WalletService_AddCredential_FullMethodName                         = "/wallet_api.v1.WalletService/AddCredential"
	WalletService_AssociateWallet_FullMethodName                       = "/wallet_api.v1.WalletService/AssociateWallet"
	WalletService_RequestPresentation_FullMethodName                   = "/wallet_api.v1.WalletService/RequestPresentation"
	WalletService_ListWalletBalanceDetails_FullMethodName              = "/wallet_api.v1.WalletService/ListWalletBalanceDetails"
	WalletService_ListTransactions_FullMethodName                      = "/wallet_api.v1.WalletService/ListTransactions"
	WalletService_GetTransactionDetail_FullMethodName                  = "/wallet_api.v1.WalletService/GetTransactionDetail"
	WalletService_PrepareTransaction_FullMethodName                    = "/wallet_api.v1.WalletService/PrepareTransaction"
	WalletService_PrepareAtomicAssetSwap_FullMethodName                = "/wallet_api.v1.WalletService/PrepareAtomicAssetSwap"
	WalletService_PrepareCrossBorderPayment_FullMethodName             = "/wallet_api.v1.WalletService/PrepareCrossBorderPayment"
	WalletService_PrepareFundsChange_FullMethodName                    = "/wallet_api.v1.WalletService/PrepareFundsChange"
	WalletService_PreparePaymentWithImplicitFundsChange_FullMethodName = "/wallet_api.v1.WalletService/PreparePaymentWithImplicitFundsChange"
	WalletService_ResumePausedTransaction_FullMethodName               = "/wallet_api.v1.WalletService/ResumePausedTransaction"
)

// WalletServiceClient is the client API for WalletService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Transacts and holds digital banknotes and bank customer information required for financial compliance, in the form of
// a W3C Verifiable Credential (https://www.w3.org/TR/vc-data-model).  This is a server side wallet solution in lieu of
// a mobile wallet, hosted by the bank on behalf of the customer who opts in to do so. Can also be used by institutions,
// e.g. a financial institution vault.
type WalletServiceClient interface {
	// Creates an owned and API key for access to future custodial wallet interactions.  Ex Could be a bank that may
	// manage many customer custodial wallets.
	CreateOwner(ctx context.Context, in *CreateOwnerRequest, opts ...grpc.CallOption) (*CreateOwnerResponse, error)
	// Creates a wallet for a given owner, which can manage the wallet.
	CreateWallet(ctx context.Context, in *CreateWalletRequest, opts ...grpc.CallOption) (*CreateWalletResponse, error)
	// List all wallets for a given owner.
	ListWallets(ctx context.Context, in *ListWalletsRequest, opts ...grpc.CallOption) (*ListWalletsResponse, error)
	// List the digital banknotes for a wallet.
	ListAssetFiles(ctx context.Context, in *ListAssetFilesRequest, opts ...grpc.CallOption) (*ListAssetFilesResponse, error)
	// List the balances of each currency in the wallet.
	ListWalletBalances(ctx context.Context, in *ListWalletBalancesRequest, opts ...grpc.CallOption) (*ListWalletBalancesResponse, error)
	// Lists the W3C Verifiable Credentials of the wallet subject.
	ListCredentials(ctx context.Context, in *ListCredentialsRequest, opts ...grpc.CallOption) (*ListCredentialsResponse, error)
	// Adds the specified W3C Verifiable Credential type for the wallet by calling out to the Credential Adapter. Based on
	// the bearer JWT token provided by User Management to ensure the caller has been authenticated and authorized.
	AddCredential(ctx context.Context, in *AddCredentialRequest, opts ...grpc.CallOption) (*AddCredentialResponse, error)
	// Associates the wallet with the account specified in the bearer JWT token provided by User Management.
	AssociateWallet(ctx context.Context, in *AssociateWalletRequest, opts ...grpc.CallOption) (*AssociateWalletResponse, error)
	// Returns the JSON Verifiable Presentation containing the PII of the subject.
	RequestPresentation(ctx context.Context, in *RequestPresentationRequest, opts ...grpc.CallOption) (*RequestPresentationResponse, error)
	// Lists more details about balances in a wallet such as how much funds are available vs reserved.
	ListWalletBalanceDetails(ctx context.Context, in *ListWalletBalanceDetailsRequest, opts ...grpc.CallOption) (*ListWalletBalanceDetailsResponse, error)
	// List transactions
	ListTransactions(ctx context.Context, in *ListTransactionsRequest, opts ...grpc.CallOption) (*ListTransactionsResponse, error)
	// Get detailed information about a transaction.
	GetTransactionDetail(ctx context.Context, in *GetTransactionDetailRequest, opts ...grpc.CallOption) (*GetTransactionDetailResponse, error)
	// Create a new transaction
	PrepareTransaction(ctx context.Context, in *PrepareTransactionRequest, opts ...grpc.CallOption) (*PrepareTransactionResponse, error)
	// Attempts to start an atomic asset swap. The call immediately returns with a `status` and `uetr` that can
	// be used to query more information about the transaction.
	PrepareAtomicAssetSwap(ctx context.Context, in *PrepareAtomicAssetSwapRequest, opts ...grpc.CallOption) (*PrepareAtomicAssetSwapResponse, error)
	// Attempts to start a cross border payment. The call immediately returns with a `status` and `uetr` that can
	// be used to query more information about the transaction.
	PrepareCrossBorderPayment(ctx context.Context, in *PrepareCrossBorderPaymentRequest, opts ...grpc.CallOption) (*PrepareCrossBorderPaymentResponse, error)
	// Attempts to start a funds change request. The call immediately returns with a `status` and `uetr` that can be used
	// to query more information about the transaction.
	PrepareFundsChange(ctx context.Context, in *PrepareFundsChangeRequest, opts ...grpc.CallOption) (*PrepareFundsChangeResponse, error)
	// Create a new transaction
	PreparePaymentWithImplicitFundsChange(ctx context.Context, in *PreparePaymentWithImplicitFundsChangeRequest, opts ...grpc.CallOption) (*PreparePaymentWithImplicitFundsChangeResponse, error)
	// Resume a transaction paused at the ProposalAck phase
	ResumePausedTransaction(ctx context.Context, in *ResumePausedTransactionRequest, opts ...grpc.CallOption) (*ResumePausedTransactionResponse, error)
}

type walletServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletServiceClient(cc grpc.ClientConnInterface) WalletServiceClient {
	return &walletServiceClient{cc}
}

func (c *walletServiceClient) CreateOwner(ctx context.Context, in *CreateOwnerRequest, opts ...grpc.CallOption) (*CreateOwnerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOwnerResponse)
	err := c.cc.Invoke(ctx, WalletService_CreateOwner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) CreateWallet(ctx context.Context, in *CreateWalletRequest, opts ...grpc.CallOption) (*CreateWalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWalletResponse)
	err := c.cc.Invoke(ctx, WalletService_CreateWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) ListWallets(ctx context.Context, in *ListWalletsRequest, opts ...grpc.CallOption) (*ListWalletsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWalletsResponse)
	err := c.cc.Invoke(ctx, WalletService_ListWallets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) ListAssetFiles(ctx context.Context, in *ListAssetFilesRequest, opts ...grpc.CallOption) (*ListAssetFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAssetFilesResponse)
	err := c.cc.Invoke(ctx, WalletService_ListAssetFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) ListWalletBalances(ctx context.Context, in *ListWalletBalancesRequest, opts ...grpc.CallOption) (*ListWalletBalancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWalletBalancesResponse)
	err := c.cc.Invoke(ctx, WalletService_ListWalletBalances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) ListCredentials(ctx context.Context, in *ListCredentialsRequest, opts ...grpc.CallOption) (*ListCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCredentialsResponse)
	err := c.cc.Invoke(ctx, WalletService_ListCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) AddCredential(ctx context.Context, in *AddCredentialRequest, opts ...grpc.CallOption) (*AddCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddCredentialResponse)
	err := c.cc.Invoke(ctx, WalletService_AddCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) AssociateWallet(ctx context.Context, in *AssociateWalletRequest, opts ...grpc.CallOption) (*AssociateWalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssociateWalletResponse)
	err := c.cc.Invoke(ctx, WalletService_AssociateWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) RequestPresentation(ctx context.Context, in *RequestPresentationRequest, opts ...grpc.CallOption) (*RequestPresentationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestPresentationResponse)
	err := c.cc.Invoke(ctx, WalletService_RequestPresentation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) ListWalletBalanceDetails(ctx context.Context, in *ListWalletBalanceDetailsRequest, opts ...grpc.CallOption) (*ListWalletBalanceDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWalletBalanceDetailsResponse)
	err := c.cc.Invoke(ctx, WalletService_ListWalletBalanceDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) ListTransactions(ctx context.Context, in *ListTransactionsRequest, opts ...grpc.CallOption) (*ListTransactionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTransactionsResponse)
	err := c.cc.Invoke(ctx, WalletService_ListTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetTransactionDetail(ctx context.Context, in *GetTransactionDetailRequest, opts ...grpc.CallOption) (*GetTransactionDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTransactionDetailResponse)
	err := c.cc.Invoke(ctx, WalletService_GetTransactionDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) PrepareTransaction(ctx context.Context, in *PrepareTransactionRequest, opts ...grpc.CallOption) (*PrepareTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareTransactionResponse)
	err := c.cc.Invoke(ctx, WalletService_PrepareTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) PrepareAtomicAssetSwap(ctx context.Context, in *PrepareAtomicAssetSwapRequest, opts ...grpc.CallOption) (*PrepareAtomicAssetSwapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareAtomicAssetSwapResponse)
	err := c.cc.Invoke(ctx, WalletService_PrepareAtomicAssetSwap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) PrepareCrossBorderPayment(ctx context.Context, in *PrepareCrossBorderPaymentRequest, opts ...grpc.CallOption) (*PrepareCrossBorderPaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareCrossBorderPaymentResponse)
	err := c.cc.Invoke(ctx, WalletService_PrepareCrossBorderPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) PrepareFundsChange(ctx context.Context, in *PrepareFundsChangeRequest, opts ...grpc.CallOption) (*PrepareFundsChangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareFundsChangeResponse)
	err := c.cc.Invoke(ctx, WalletService_PrepareFundsChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) PreparePaymentWithImplicitFundsChange(ctx context.Context, in *PreparePaymentWithImplicitFundsChangeRequest, opts ...grpc.CallOption) (*PreparePaymentWithImplicitFundsChangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreparePaymentWithImplicitFundsChangeResponse)
	err := c.cc.Invoke(ctx, WalletService_PreparePaymentWithImplicitFundsChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) ResumePausedTransaction(ctx context.Context, in *ResumePausedTransactionRequest, opts ...grpc.CallOption) (*ResumePausedTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumePausedTransactionResponse)
	err := c.cc.Invoke(ctx, WalletService_ResumePausedTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletServiceServer is the server API for WalletService service.
// All implementations must embed UnimplementedWalletServiceServer
// for forward compatibility
//
// Transacts and holds digital banknotes and bank customer information required for financial compliance, in the form of
// a W3C Verifiable Credential (https://www.w3.org/TR/vc-data-model).  This is a server side wallet solution in lieu of
// a mobile wallet, hosted by the bank on behalf of the customer who opts in to do so. Can also be used by institutions,
// e.g. a financial institution vault.
type WalletServiceServer interface {
	// Creates an owned and API key for access to future custodial wallet interactions.  Ex Could be a bank that may
	// manage many customer custodial wallets.
	CreateOwner(context.Context, *CreateOwnerRequest) (*CreateOwnerResponse, error)
	// Creates a wallet for a given owner, which can manage the wallet.
	CreateWallet(context.Context, *CreateWalletRequest) (*CreateWalletResponse, error)
	// List all wallets for a given owner.
	ListWallets(context.Context, *ListWalletsRequest) (*ListWalletsResponse, error)
	// List the digital banknotes for a wallet.
	ListAssetFiles(context.Context, *ListAssetFilesRequest) (*ListAssetFilesResponse, error)
	// List the balances of each currency in the wallet.
	ListWalletBalances(context.Context, *ListWalletBalancesRequest) (*ListWalletBalancesResponse, error)
	// Lists the W3C Verifiable Credentials of the wallet subject.
	ListCredentials(context.Context, *ListCredentialsRequest) (*ListCredentialsResponse, error)
	// Adds the specified W3C Verifiable Credential type for the wallet by calling out to the Credential Adapter. Based on
	// the bearer JWT token provided by User Management to ensure the caller has been authenticated and authorized.
	AddCredential(context.Context, *AddCredentialRequest) (*AddCredentialResponse, error)
	// Associates the wallet with the account specified in the bearer JWT token provided by User Management.
	AssociateWallet(context.Context, *AssociateWalletRequest) (*AssociateWalletResponse, error)
	// Returns the JSON Verifiable Presentation containing the PII of the subject.
	RequestPresentation(context.Context, *RequestPresentationRequest) (*RequestPresentationResponse, error)
	// Lists more details about balances in a wallet such as how much funds are available vs reserved.
	ListWalletBalanceDetails(context.Context, *ListWalletBalanceDetailsRequest) (*ListWalletBalanceDetailsResponse, error)
	// List transactions
	ListTransactions(context.Context, *ListTransactionsRequest) (*ListTransactionsResponse, error)
	// Get detailed information about a transaction.
	GetTransactionDetail(context.Context, *GetTransactionDetailRequest) (*GetTransactionDetailResponse, error)
	// Create a new transaction
	PrepareTransaction(context.Context, *PrepareTransactionRequest) (*PrepareTransactionResponse, error)
	// Attempts to start an atomic asset swap. The call immediately returns with a `status` and `uetr` that can
	// be used to query more information about the transaction.
	PrepareAtomicAssetSwap(context.Context, *PrepareAtomicAssetSwapRequest) (*PrepareAtomicAssetSwapResponse, error)
	// Attempts to start a cross border payment. The call immediately returns with a `status` and `uetr` that can
	// be used to query more information about the transaction.
	PrepareCrossBorderPayment(context.Context, *PrepareCrossBorderPaymentRequest) (*PrepareCrossBorderPaymentResponse, error)
	// Attempts to start a funds change request. The call immediately returns with a `status` and `uetr` that can be used
	// to query more information about the transaction.
	PrepareFundsChange(context.Context, *PrepareFundsChangeRequest) (*PrepareFundsChangeResponse, error)
	// Create a new transaction
	PreparePaymentWithImplicitFundsChange(context.Context, *PreparePaymentWithImplicitFundsChangeRequest) (*PreparePaymentWithImplicitFundsChangeResponse, error)
	// Resume a transaction paused at the ProposalAck phase
	ResumePausedTransaction(context.Context, *ResumePausedTransactionRequest) (*ResumePausedTransactionResponse, error)
	mustEmbedUnimplementedWalletServiceServer()
}

// UnimplementedWalletServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWalletServiceServer struct {
}

func (UnimplementedWalletServiceServer) CreateOwner(context.Context, *CreateOwnerRequest) (*CreateOwnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOwner not implemented")
}
func (UnimplementedWalletServiceServer) CreateWallet(context.Context, *CreateWalletRequest) (*CreateWalletResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWallet not implemented")
}
func (UnimplementedWalletServiceServer) ListWallets(context.Context, *ListWalletsRequest) (*ListWalletsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWallets not implemented")
}
func (UnimplementedWalletServiceServer) ListAssetFiles(context.Context, *ListAssetFilesRequest) (*ListAssetFilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAssetFiles not implemented")
}
func (UnimplementedWalletServiceServer) ListWalletBalances(context.Context, *ListWalletBalancesRequest) (*ListWalletBalancesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWalletBalances not implemented")
}
func (UnimplementedWalletServiceServer) ListCredentials(context.Context, *ListCredentialsRequest) (*ListCredentialsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCredentials not implemented")
}
func (UnimplementedWalletServiceServer) AddCredential(context.Context, *AddCredentialRequest) (*AddCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCredential not implemented")
}
func (UnimplementedWalletServiceServer) AssociateWallet(context.Context, *AssociateWalletRequest) (*AssociateWalletResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssociateWallet not implemented")
}
func (UnimplementedWalletServiceServer) RequestPresentation(context.Context, *RequestPresentationRequest) (*RequestPresentationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestPresentation not implemented")
}
func (UnimplementedWalletServiceServer) ListWalletBalanceDetails(context.Context, *ListWalletBalanceDetailsRequest) (*ListWalletBalanceDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWalletBalanceDetails not implemented")
}
func (UnimplementedWalletServiceServer) ListTransactions(context.Context, *ListTransactionsRequest) (*ListTransactionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTransactions not implemented")
}
func (UnimplementedWalletServiceServer) GetTransactionDetail(context.Context, *GetTransactionDetailRequest) (*GetTransactionDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransactionDetail not implemented")
}
func (UnimplementedWalletServiceServer) PrepareTransaction(context.Context, *PrepareTransactionRequest) (*PrepareTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareTransaction not implemented")
}
func (UnimplementedWalletServiceServer) PrepareAtomicAssetSwap(context.Context, *PrepareAtomicAssetSwapRequest) (*PrepareAtomicAssetSwapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareAtomicAssetSwap not implemented")
}
func (UnimplementedWalletServiceServer) PrepareCrossBorderPayment(context.Context, *PrepareCrossBorderPaymentRequest) (*PrepareCrossBorderPaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareCrossBorderPayment not implemented")
}
func (UnimplementedWalletServiceServer) PrepareFundsChange(context.Context, *PrepareFundsChangeRequest) (*PrepareFundsChangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareFundsChange not implemented")
}
func (UnimplementedWalletServiceServer) PreparePaymentWithImplicitFundsChange(context.Context, *PreparePaymentWithImplicitFundsChangeRequest) (*PreparePaymentWithImplicitFundsChangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PreparePaymentWithImplicitFundsChange not implemented")
}
func (UnimplementedWalletServiceServer) ResumePausedTransaction(context.Context, *ResumePausedTransactionRequest) (*ResumePausedTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumePausedTransaction not implemented")
}
func (UnimplementedWalletServiceServer) mustEmbedUnimplementedWalletServiceServer() {}

// UnsafeWalletServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalletServiceServer will
// result in compilation errors.
type UnsafeWalletServiceServer interface {
	mustEmbedUnimplementedWalletServiceServer()
}

func RegisterWalletServiceServer(s grpc.ServiceRegistrar, srv WalletServiceServer) {
	s.RegisterService(&WalletService_ServiceDesc, srv)
}

func _WalletService_CreateOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).CreateOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_CreateOwner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).CreateOwner(ctx, req.(*CreateOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_CreateWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).CreateWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_CreateWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).CreateWallet(ctx, req.(*CreateWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_ListWallets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWalletsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).ListWallets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_ListWallets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).ListWallets(ctx, req.(*ListWalletsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_ListAssetFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAssetFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).ListAssetFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_ListAssetFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).ListAssetFiles(ctx, req.(*ListAssetFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_ListWalletBalances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWalletBalancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).ListWalletBalances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_ListWalletBalances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).ListWalletBalances(ctx, req.(*ListWalletBalancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_ListCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).ListCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_ListCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).ListCredentials(ctx, req.(*ListCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_AddCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).AddCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_AddCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).AddCredential(ctx, req.(*AddCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_AssociateWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssociateWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).AssociateWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_AssociateWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).AssociateWallet(ctx, req.(*AssociateWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_RequestPresentation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestPresentationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).RequestPresentation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_RequestPresentation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).RequestPresentation(ctx, req.(*RequestPresentationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_ListWalletBalanceDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWalletBalanceDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).ListWalletBalanceDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_ListWalletBalanceDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).ListWalletBalanceDetails(ctx, req.(*ListWalletBalanceDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_ListTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).ListTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_ListTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).ListTransactions(ctx, req.(*ListTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetTransactionDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetTransactionDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_GetTransactionDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetTransactionDetail(ctx, req.(*GetTransactionDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_PrepareTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).PrepareTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_PrepareTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).PrepareTransaction(ctx, req.(*PrepareTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_PrepareAtomicAssetSwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareAtomicAssetSwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).PrepareAtomicAssetSwap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_PrepareAtomicAssetSwap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).PrepareAtomicAssetSwap(ctx, req.(*PrepareAtomicAssetSwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_PrepareCrossBorderPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareCrossBorderPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).PrepareCrossBorderPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_PrepareCrossBorderPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).PrepareCrossBorderPayment(ctx, req.(*PrepareCrossBorderPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_PrepareFundsChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareFundsChangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).PrepareFundsChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_PrepareFundsChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).PrepareFundsChange(ctx, req.(*PrepareFundsChangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_PreparePaymentWithImplicitFundsChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreparePaymentWithImplicitFundsChangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).PreparePaymentWithImplicitFundsChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_PreparePaymentWithImplicitFundsChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).PreparePaymentWithImplicitFundsChange(ctx, req.(*PreparePaymentWithImplicitFundsChangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_ResumePausedTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumePausedTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).ResumePausedTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_ResumePausedTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).ResumePausedTransaction(ctx, req.(*ResumePausedTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WalletService_ServiceDesc is the grpc.ServiceDesc for WalletService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WalletService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wallet_api.v1.WalletService",
	HandlerType: (*WalletServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOwner",
			Handler:    _WalletService_CreateOwner_Handler,
		},
		{
			MethodName: "CreateWallet",
			Handler:    _WalletService_CreateWallet_Handler,
		},
		{
			MethodName: "ListWallets",
			Handler:    _WalletService_ListWallets_Handler,
		},
		{
			MethodName: "ListAssetFiles",
			Handler:    _WalletService_ListAssetFiles_Handler,
		},
		{
			MethodName: "ListWalletBalances",
			Handler:    _WalletService_ListWalletBalances_Handler,
		},
		{
			MethodName: "ListCredentials",
			Handler:    _WalletService_ListCredentials_Handler,
		},
		{
			MethodName: "AddCredential",
			Handler:    _WalletService_AddCredential_Handler,
		},
		{
			MethodName: "AssociateWallet",
			Handler:    _WalletService_AssociateWallet_Handler,
		},
		{
			MethodName: "RequestPresentation",
			Handler:    _WalletService_RequestPresentation_Handler,
		},
		{
			MethodName: "ListWalletBalanceDetails",
			Handler:    _WalletService_ListWalletBalanceDetails_Handler,
		},
		{
			MethodName: "ListTransactions",
			Handler:    _WalletService_ListTransactions_Handler,
		},
		{
			MethodName: "GetTransactionDetail",
			Handler:    _WalletService_GetTransactionDetail_Handler,
		},
		{
			MethodName: "PrepareTransaction",
			Handler:    _WalletService_PrepareTransaction_Handler,
		},
		{
			MethodName: "PrepareAtomicAssetSwap",
			Handler:    _WalletService_PrepareAtomicAssetSwap_Handler,
		},
		{
			MethodName: "PrepareCrossBorderPayment",
			Handler:    _WalletService_PrepareCrossBorderPayment_Handler,
		},
		{
			MethodName: "PrepareFundsChange",
			Handler:    _WalletService_PrepareFundsChange_Handler,
		},
		{
			MethodName: "PreparePaymentWithImplicitFundsChange",
			Handler:    _WalletService_PreparePaymentWithImplicitFundsChange_Handler,
		},
		{
			MethodName: "ResumePausedTransaction",
			Handler:    _WalletService_ResumePausedTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wallet_api/v1/wallet.proto",
}
